//const MongoClient = require('mongodb').MongoClient;
const {MongoClient, ObjectId} = require('mongodb');

var myId = new ObjectId();
console.log(`Key Generated by Method: ${myId}`);

MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, db) => {
    
    if (err) {
        return console.log('Unable to connect to MongoDB server');
    }



    console.log('Connected to MongoDB server');



    // db.collection('Todo').insertOne( {
    //     text: 'Something to do',
    //     completed: false
    // }, (err, res) => {
    //     if (err) {
    //         return console.log('Unable to insert todo', err)
    //     }

    //     console.log(JSON.stringify(res.ops, undefined, 2));
    // });

    db.collection('Users').insertOne( {
        name: "Corrado Valente",
        age: 23,
        location: "Palagiano (TA)"
    }, (err, res) => {
        if (err) {
            return console.log('Unable to insert todo', err)
        }

        console.log(`Document ObjectID: ${JSON.stringify(res.ops[0]._id, undefined, 2)}`);
        console.log(`TimeStamp: ${res.ops[0]._id.getTimestamp()}`)
    });


    db.close();

})
